// nitro-ssr-vue-router/host/app/components/Counter.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

const count = ref(0);
const mounted = ref(false);

onMounted(() => {
  mounted.value = true;
});
</script>

<template>
  <button v-if="mounted" class="counter" @click="count++">Host counter: {{ count }}</button>
</template>

<style scoped>
.counter {
  background-color: rgb(246, 179, 82);
  border: 0 solid #e2e8f0;
  border-radius: 4px;
  color: rgb(24, 24, 24);
  cursor: pointer;
  font-weight: 700;
  margin-top: 10px;
  padding: 8px 16px;
}
</style>

// react-ssr/host/src/components/Counter.tsx
import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);

  return (
    <button
      type="button"
      style={{
        border: "0 solid #e2e8f0",
        marginTop: "10px",
        backgroundColor: "rgb(246, 179, 82)",
        borderRadius: ".25rem",
        fontWeight: "700",
        padding: ".5rem 1rem",
        color: "rgb(24, 24, 24)",
        cursor: "pointer",
      }}
      onClick={() => setCount(count + 1)}
    >
      Host counter: {count}
    </button>
  );
}
