// react-ssr/remote-a/src/App.tsx
import { lazy, Suspense, useEffect } from "react";
import RemoteCard from "./components/RemoteCard";

const RemoteB = lazy(() => import("remote_b/remote-app"));

export default function RemoteApp() {
  useEffect(() => {
    console.log("Remote useEffect (remote_a)");
  }, []);

  return (
    <RemoteCard title="I'm the remote app">
      <div style={{ marginTop: 16, display: "flex", justifyContent: "center" }}>
        <Suspense fallback={null}>
          <RemoteB />
        </Suspense>
      </div>
    </RemoteCard>
  );
}

// vue-ssr/remote-a/src/App.vue
<script setup lang="ts">
import { defineAsyncComponent } from "vue";
import RemoteCard from "./components/RemoteCard.vue";

const RemoteB = defineAsyncComponent(() => import("remote_b/remote-app"));
</script>

<template>
  <RemoteCard title="I'm the remote app">
    <div style="margin-top: 16px; display: flex; justify-content: center">
      <Suspense>
        <RemoteB />
      </Suspense>
    </div>
  </RemoteCard>
</template>
