// vue-ssr/remote-a/src/components/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
</script>

<template>
  <button
    type="button"
    style="
      border: 0 solid #e2e8f0;
      margin-top: 10px;
      background-color: rgb(246, 179, 82);
      border-radius: 0.25rem;
      font-weight: 700;
      padding: 0.5rem 1rem;
      color: rgb(24, 24, 24);
      cursor: pointer;
    "
    @click="count++"
  >
    Remote counter: {{ count }}
  </button>
</template>

// react-ssr/remote-c/src/components/Counter.tsx
import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);

  return (
    <button
      type="button"
      style={{
        border: "0 solid #e2e8f0",
        marginTop: "10px",
        backgroundColor: "rgb(246, 179, 82)",
        borderRadius: ".25rem",
        fontWeight: "700",
        padding: ".5rem 1rem",
        color: "rgb(24, 24, 24)",
        cursor: "pointer",
      }}
      onClick={() => setCount(count + 1)}
    >
      Remote counter: {count}
    </button>
  );
}
